
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebTableti
{

using System;
    using System.Collections.Generic;
    
public partial class MACHINES_SETUP
{

    public string PlantCode { get; set; }

    public string RoomCode { get; set; }

    public string GroupCode { get; set; }

    public int MachCode { get; set; }

    public string Server { get; set; }

    public string CustomFile { get; set; }

    public Nullable<int> Interface { get; set; }

    public string Printer { get; set; }

    public string CalendarTableName { get; set; }

    public string DiameterCylinder { get; set; }

    public Nullable<int> Display { get; set; }

    public Nullable<int> Needles { get; set; }

    public string Email { get; set; }

    public string ModelCode { get; set; }

    public string MachineId { get; set; }

    public Nullable<int> RowCode { get; set; }

}

}
