//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTableti
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINES
    {
        public long ID_TUB { get; set; }
        public string PlantCode { get; set; }
        public string RoomCode { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> MachCode { get; set; }
        public Nullable<int> MachNumber { get; set; }
        public string IpAddress { get; set; }
        public string SwVer { get; set; }
        public string EpromVer { get; set; }
        public Nullable<int> State { get; set; }
        public string OrderCode { get; set; }
        public string StyleCode { get; set; }
        public string StSize { get; set; }
        public string StColor { get; set; }
        public string StLot { get; set; }
        public string Program { get; set; }
        public Nullable<int> SizePr { get; set; }
        public Nullable<int> TimeOn { get; set; }
        public Nullable<int> TimeOff { get; set; }
        public Nullable<int> FunctionKey { get; set; }
        public Nullable<int> Pieces { get; set; }
        public Nullable<int> TargetOrder { get; set; }
        public Nullable<int> ShiftPieces { get; set; }
        public Nullable<int> LastPieces { get; set; }
        public Nullable<int> BagPieces { get; set; }
        public Nullable<int> BagTarget { get; set; }
        public Nullable<double> IdealCycle { get; set; }
        public Nullable<double> LastCycle { get; set; }
        public Nullable<int> LastStopCode { get; set; }
        public Nullable<int> Step { get; set; }
        public Nullable<int> Discards { get; set; }
        public Nullable<int> WorkEfficiency { get; set; }
        public Nullable<int> TimeEfficiency { get; set; }
        public Nullable<int> Shift { get; set; }
        public string StopFrequency { get; set; }
        public string PairCode { get; set; }
        public Nullable<int> LastTimeOn { get; set; }
        public Nullable<int> LastTimeOff { get; set; }
        public Nullable<int> ShiftDiscards { get; set; }
        public Nullable<int> LastDiscards { get; set; }
        public Nullable<System.DateTime> DateStartShift { get; set; }
        public string NauVer { get; set; }
        public string BalancingCode { get; set; }
        public Nullable<int> Transient { get; set; }
        public string LinkProgram { get; set; }
        public string NameProg1 { get; set; }
        public Nullable<int> TargetProg1 { get; set; }
        public Nullable<int> PiecesProg1 { get; set; }
        public Nullable<int> LastPiecesProg1 { get; set; }
        public Nullable<double> CycleTimeProg1 { get; set; }
        public string NameProg2 { get; set; }
        public Nullable<int> TargetProg2 { get; set; }
        public Nullable<int> PiecesProg2 { get; set; }
        public Nullable<int> LastPiecesProg2 { get; set; }
        public Nullable<double> CycleTimeProg2 { get; set; }
        public string NameProg3 { get; set; }
        public Nullable<int> TargetProg3 { get; set; }
        public Nullable<int> PiecesProg3 { get; set; }
        public Nullable<int> LastPiecesProg3 { get; set; }
        public Nullable<double> CycleTimeProg3 { get; set; }
        public string NameProg4 { get; set; }
        public Nullable<int> TargetProg4 { get; set; }
        public Nullable<int> PiecesProg4 { get; set; }
        public Nullable<int> LastPiecesProg4 { get; set; }
        public Nullable<double> CycleTimeProg4 { get; set; }
        public string NameProg5 { get; set; }
        public Nullable<int> TargetProg5 { get; set; }
        public Nullable<int> PiecesProg5 { get; set; }
        public Nullable<int> LastPiecesProg5 { get; set; }
        public Nullable<double> CycleTimeProg5 { get; set; }
        public string RespoCode { get; set; }
        public string MachineId { get; set; }
        public Nullable<int> ShiftDisabled { get; set; }
        public Nullable<int> DigitalInputs { get; set; }
        public Nullable<int> ManualStopInProd { get; set; }
        public string ModelCode { get; set; }
    }
}
