

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebTableti
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class dbNautilusEntities1 : DbContext
{
    public dbNautilusEntities1()
        : base("name=dbNautilusEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<TUBLAFermi> TUBLAFermi { get; set; }

    public DbSet<OPERATORS> OPERATORS { get; set; }

    public DbSet<TUBLAInfo> TUBLAInfo { get; set; }

    public DbSet<RemontMach> RemontMach { get; set; }

    public DbSet<MACHINES_SETUP> MACHINES_SETUP { get; set; }

}

}

