
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebTableti
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class RemontMach
{

    public int IdRemonta { get; set; }


    [DisplayName("Datum kreiranja")]
    [DataType(DataType.Date)]
    public Nullable<System.DateTime> DatumOd { get; set; }

    public string Opis { get; set; }

    [DisplayName("Broj mašine")]
    public Nullable<int> MachCode { get; set; }

    [DisplayName("Matricola")]
    public string MachineId { get; set; }

    [DisplayName("Datum završetka")]
    [DataType(DataType.Date)]
    public Nullable<System.DateTime> DatumPov { get; set; }

    public string Korisnik { get; set; }

}

}
