
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebTableti
{

using System;
    using System.Collections.Generic;
    
public partial class TUBLAFermi
{

    public int ID { get; set; }

    public bool Status { get; set; }

    public string UniqueID { get; set; }

}

}
